### ISSUE TITLE
Outofmemory

### ISSUE THREAD

**Issue by Sotatek-DuyHoang** [instantX-research/Regional-Prompting-FLUX#13]
When I run file infer_flux_regional.py. An error appears:

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 23.43 GiB of which 4.06 MiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 23.03 GiB is allocated by PyTorch, and 15.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by antonioo-c** [comment]
@Sotatek-DuyHoang Sorry for the late response. the memory overflow was due to the native flux. You can try offloading the model or use the ComfyUI workflow with some memory-saving settups (which I am not familiar with).
