### ISSUE TITLE
Not able to reproduce PuLID examples

### ISSUE THREAD

**Issue by artmamedov** [instantX-research/Regional-Prompting-FLUX#14]
Hi!

I setup as you described and I'm not able to reproduce the multiple PuLID examples. Mine ends up coming out like this. I have the appropriate diffusers but is it possible that it needs a specific branch of PuLID as well? I just installed latest. I also copied the transformer_flux_pulid.py into diffusers, so I don't think that's it. Please advise. Thank you!

![image](https://github.com/user-attachments/assets/da56ca58-7061-4d1f-9914-215e5cc95faa)

**Comment by artmamedov** [comment]
Nevermind, just the ordering was weird. Had to reinstall diffusers after the transformer copy step.

**Comment by DeepthiSudharsan** [comment]
Hi @artmamedov , could you please help me understand what was the reordering change you made? I am facing multiple issues while trying to reproduce the PuLID examples starting from "No module named 'diffusers.image_processor'" to "TypeError: FluxTransformer2DModel.forward() got an unexpected keyword argument 'encoder_hidden_states_base'". I followed the setup steps given in the README but seem to be coming across these issues. Were there any other things you had to install, setup or do differently compared to the steps given in the README?
