### ISSUE TITLE
PuLID start_step Support

### ISSUE THREAD

**Issue by lordsoffallen** [instantX-research/Regional-Prompting-FLUX#15]
Is it possible to get support for start_step parameter? 

`timestep to start inserting ID: The smaller the value, the higher the fidelity, but the lower the editability; the higher the value, the lower the fidelity, but the higher the editability. The recommended range for this value is between 0 and 4. For photorealistic scenes, we recommend using 4; for stylized scenes, we recommend using 0-1. If you are not satisfied with the similarity, you can lower this value; conversely, if you are not satisfied with the editability, you can increase this value`

Right now we are not able to control afaik and pictures are looking like portraits with face looking at viewer.

**Comment by lordsoffallen** [comment]
Adding on this, lowering id_weight creates better looking pictures but character resembles is not there which i think it could be improved by bringing this support.

**Comment by antonioo-c** [comment]
@lordsoffallen try setting up start_step in here 
https://github.com/instantX-research/Regional-Prompting-FLUX/blob/60111799b14643a0df8ff3fd0d4defecdd8c55f0/pipeline_flux_regional_pulid.py#L724

change into
```python
'id_embeddings': id_embeddings if i >= start_step else None
```

the start_step should be working same as in the [PULID doc](https://github.com/ToTheBeginning/PuLID/blob/ad1fe74a49d82fb21bc9d89cb769fd7d823a631d/docs/pulid_for_flux.md#useful-tips)

**Comment by lordsoffallen** [comment]
> @lordsoffallen try setting up start_step in here
> 
> https://github.com/instantX-research/Regional-Prompting-FLUX/blob/60111799b14643a0df8ff3fd0d4defecdd8c55f0/pipeline_flux_regional_pulid.py#L724
> 
> change into
> 
> ```python
> 'id_embeddings': id_embeddings if i >= start_step else None
> ```
> 
> the start_step should be working same as in the [PULID doc](https://github.com/ToTheBeginning/PuLID/blob/ad1fe74a49d82fb21bc9d89cb769fd7d823a631d/docs/pulid_for_flux.md#useful-tips)

Thanks for the pointer, I did change the id_weights to 0 but that didn't help. Here is what I changed there:

_id_weights = joint_attention_kwargs['id_weights'] if 'id_weights' in joint_attention_kwargs else None
if i < pulid_start_step:
    _id_weights = len(_id_weights) * [0.0]

By looking into the code, this should also work the same way unless im missing something. If pulid is disabled (setting weights to 0 for all steps), generated image is fine but when pulid is enabled, i get the character looking like posing all the time. I guess it's not fully solved in the pulid yet..

**Comment by antonioo-c** [comment]
Yes, setting the id_weights to 0 does work the same (though taking up more computational cost than disabling it directly). So if you don't see a difference changing the start_step, then probably such a phenomenon could be seen in the original pulid as well.

**Comment by lordsoffallen** [comment]
> Yes, setting the id_weights to 0 does work the same (though taking up more computational cost than disabling it directly). So if you don't see a difference changing the start_step, then probably such a phenomenon could be seen in the original pulid as well.

That's what i thought as well. One last question on this, do you think dynamically changing id_weights would maybe have the desired affect somehow? :thinking: Maybe starting with lower and increasing as the steps go up. I wanted to run that as an experiment tomorrow but wanted to see if you happen to have some suggestions.

**Comment by antonioo-c** [comment]
> > Yes, setting the id_weights to 0 does work the same (though taking up more computational cost than disabling it directly). So if you don't see a difference changing the start_step, then probably such a phenomenon could be seen in the original pulid as well.
> 
> That's what i thought as well. One last question on this, do you think dynamically changing id_weights would maybe have the desired affect somehow? 🤔 Maybe starting with lower and increasing as the steps go up. I wanted to run that as an experiment tomorrow but wanted to see if you happen to have some suggestions.

No, sorry, I have not tried that before. If you are willing to share your experiments here, I will leave this issue open for you.

**Comment by lordsoffallen** [comment]
I ran this experiment for linearly decreasing/increasing and sigmoid increasing/decreasing manner. Multiple character scenes does not work at all. When pulid is involved regional prompting is mostly wrong due to pulid effect. Without pulid it works as expected and a lot better.

Only relevant thing that when using sigmoid weight decreasing is that single character scene could show character a bit more authentic.

**Comment by antonioo-c** [comment]
> I ran this experiment for linearly decreasing/increasing and sigmoid increasing/decreasing manner. Multiple character scenes does not work at all. When pulid is involved regional prompting is mostly wrong due to pulid effect. Without pulid it works as expected and a lot better.
> 
> Only relevant thing that when using sigmoid weight decreasing is that single character scene could show character a bit more authentic.

That's interesting to find out, thank you for the work! Would you like to show some more images as results?

**Comment by lordsoffallen** [comment]
A bit hard to put them here but i'll share some examples:

A scene with 3 guys, one holding a red tube. This one is with pulid **disabled**. Everything works as expected here.
![1_46578686](https://github.com/user-attachments/assets/5874685b-620d-4c03-afa3-3a7dbf8fda0d)

Same scene with providing 3 different image ids. None of them looks like in ids. I used `sigmoid descending` function to reduce id weight after each iteration. (starts at id_weight 1.0)
![chap1 7_1_8912838_g4_id1 0_base0 1_mask6_pulid3_d1s1_1280px](https://github.com/user-attachments/assets/07ea1dbf-b3f4-41b4-92cf-44de56494b18)

One of many bad outputs. Using `sigmoid descending` method. Mostly missing other characters, non relevant id. I rarely get 3 characters in the scene.
![chap1 7_1_8912838_g4_id1 0_base0 1_mask10_pulid2_d1s1_1280px](https://github.com/user-attachments/assets/033e58b1-cf91-4b09-a209-c6e225cca432)

Using `linearly descreasing` method. First character on the left has the id similarity while the other two not. And when they look similar, it changes the scene and posture of the character so it looks unnatural. 
![chap1 7_1_9187238894_g4_id1 0_base0 1_mask6_pulid2_d1s1_1280px](https://github.com/user-attachments/assets/ea353921-0d9f-4825-9bf9-7dec380d649e)

Following the same parameter space as above, here is one that just completely messed up. Character face is similar but it does not 
![chap1 7_1_8912838_g4_id1 0_base0 1_mask10_pulid2_d1s1_1280px](https://github.com/user-attachments/assets/6b0cd4bf-743a-4a37-8994-905786e78505)

A new scene with two characters, both have the good id resemblance but extremly sensitive to hyperparams. This one is with pulid start step 2 and any other value loses the id resemblance completely.  
![chap1 7_2_9187238894_g4_id1 0_base0 1_mask6_pulid2_d1s1_1280px](https://github.com/user-attachments/assets/099d12e5-9fcf-476a-ab2e-94f9c7c1d6fe)

Now for the single character scenes i mentioned earlier:

This one is still using linear descreasing, results are similar to other pulid outputs where the person always looking at me
![chap2 3_1_8912838_g4_id1 0_base0 1_mask6_pulid3_d1s1_1280px](https://github.com/user-attachments/assets/d9075947-baf8-4c44-ac5e-6fd68a9b6edf)

and same thing this time with `sigmoid descending` makes it more natural with a slight decrease in id similarity.
![chap2 3_1_8912838_g4_id1 0_base0 1_mask6_pulid2_d1s1_1280px](https://github.com/user-attachments/assets/c7c0ea30-d4e2-4c66-b343-5fa4823e28fd)

I hope this creates some light into it. My conclusion is that during image generation regional + pulid is just not working well. Regional itself work but perhaps after the image is created pulid could be applied somehow but not together.

**Comment by antonioo-c** [comment]
@lordsoffallen Thank you for the experimental results! I guess there could be more to be done with pulid + regional-prompting-flux.
