### ISSUE TITLE
Unused Code Piece

### ISSUE THREAD

**Issue by lordsoffallen** [instantX-research/Regional-Prompting-FLUX#16]
I've noticed that the following lines are not used anywhere else:

https://github.com/instantX-research/Regional-Prompting-FLUX/blob/60111799b14643a0df8ff3fd0d4defecdd8c55f0/pipeline_flux_regional.py#L369-L370

I assume it's safe to remove them? I wanted to make sure it was not a bug or anything.

**Comment by antonioo-c** [comment]
@lordsoffallen Yes, you can remove those; they were not used in the code. Thank you for pointing that out.
