### ISSUE TITLE
Do we have plans for comfyui integration?

### ISSUE THREAD

**Issue by Pancat009** [instantX-research/Regional-Prompting-FLUX#6]
would be great to use like IPA or ControlNet via ComfyUI, not sure if we have any plan for comfyui integration?

**Comment by antonioo-c** [comment]
@Pancat009  I read that people are working on it already, see https://www.reddit.com/r/FluxAI/comments/1gk30bw/comment/lvi5fdj/?context=3. I will put up a notice if it's completed. Stay tuned!

**Comment by antonioo-c** [comment]
@Pancat009 Hi, please check if this community support fits your need. https://github.com/instantX-research/Regional-Prompting-FLUX?tab=readme-ov-file#community-resources
