### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by cvmaker93** [instantX-research/Regional-Prompting-FLUX#7]
When I ran the program, I encountered a Floating point exception error, which occurred when calling the self. transformar() function. Can you give me some troubleshooting ideas

<img width="389" alt="企业微信20241107-151754@2x" src="https://github.com/user-attachments/assets/9ef908a8-c3e1-4995-b843-8f505934c2c5">

**Comment by antonioo-c** [comment]
@cvmaker93 Which GPU are you working on? Please provide your device environments in the issue.
