### ISSUE TITLE
run on 24gb vram?

### ISSUE THREAD

**Issue by petmycat** [instantX-research/Regional-Prompting-FLUX#8]
I have a 4090 24gb vram card, but apparently running the infer_flux_regional.py file consumes way more than 24gb. I tried various ways, including fp8 version of the dev model, and schnell, but vram still exceed 24gb. So is it possible to run this on 24gb vram at all? If so, some help would be very much appreciated.

**Comment by antonioo-c** [comment]
@petmycat Sorry for the late response, can you try the offloading method I mentioned in https://github.com/instantX-research/Regional-Prompting-FLUX/issues/9#issuecomment-2469697149. That might help ease the problem. Thank you.

**Comment by petmycat** [comment]
> @petmycat Sorry for the late response, can you try the offloading method I mentioned in [#9 (comment)](https://github.com/instantX-research/Regional-Prompting-FLUX/issues/9#issuecomment-2469697149). That might help ease the problem. Thank you.

Thanks! This method worked with Flux.schnell, before it took up to an hour for inference 20 steps, now it takes 3-5 minutes. I'm on windows, but if someone were to use this on linux, inference time could potentially be under 1 minute.

**Comment by antonioo-c** [comment]
Good to know that, I will close this issue then.
